### ISSUE TITLE
Error when creating users table

### ISSUE THREAD

**Issue by hikarimn** [hamzaehsan97/Guestimate#2]
Error when creating a user table. Syntax error?

![Screen Shot 2019-06-28 at 4 31 47 PM](https://user-images.githubusercontent.com/37006149/60369644-5200cc80-99c2-11e9-9aaa-5ad0b51cb1c4.png)

**Comment by hamzaehsan97** [comment]
While creating a table with SQL it is important to mention a variable type for each column. In this case, the variable type for superPower is missing. Here's a corrected version. Let me know if it works.

CREATE TABLE users (
    id int AUTO_INCREMENT,
    firstName varchar(255),
    lastName varchar(255),
    email varchar(255),
    password varchar(255),
    company varchar(255),
    superPower varchar(255),
    PRIMARY KEY (id)
);
